-- 회원 테이블

drop table member;

CREATE TABLE MEMBER(
IDX NUMBER(8) CONSTRAINT MEMBER_IDX_PK PRIMARY KEY,
NAME VARCHAR2(3) NOT NULL,
USERID VARCHAR2(20) CONSTRAINT MEMBER_USERID_UK UNIQUE,
PWD VARCHAR2(20) NOT NULL,
HP1 CHAR(3) NOT NULL,
HP2 CHAR(4) NOT NULL,
HP3 CHAR(4) NOT NULL,
POST CHAR(5), -- 우편번호 테이블을 참조하는 외래키
ADDR1 VARCHAR2(200), -- 주소
ADDR2 VARCHAR2(200),
INDATE DATE DEFAULT SYSDATE, -- 등록일
MILEAGE NUMBER(10) DEFAULT 1000, -- 마일리지
MSTATE NUMBER(2) DEFAULT 0 -- 회원상태(활동회원 0, 정지회원 1, 탈퇴회원 -1)
CONSTRAINT MEMBER_MSTATE_CK CHECK(MSTATE IN (0,1,-1))
);

DSEC MEMBER;

DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;